<?php

$data = include dirname(__FILE__).'/../../Mobile-Detect/tests/UA_List.inc.php';

$out = "/* this file was generated by export-testdata.php */\n\n";
$out .= "var mobilePerVendor =\n";

$out .= json_encode($data, JSON_PRETTY_PRINT);

$out .= ";\n\n";

$out .= "if (typeof module !== 'undefined') { module.exports = mobilePerVendor; }";

file_put_contents(dirname(__FILE__).'/../tests/data/user-agents.js', $out);

